export { default as HeroSection } from './HeroSection'
export { default as ServiceSection } from './ServiceSection'
export { default as AboutSection } from './about'
export { default as CTASection } from './CTASection'
export { default as TestimonialSection } from './TestimonialSection'
export { default as ContactSection } from './contact'
